### ISSUE TITLE
Kernel update breaks entire system linux-image-6.8.0-76060800daily20240311-generic+

### ISSUE THREAD

**Issue by sedit10n** [pop-os/pop#3277]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
linux-image-6.8.0-76060800daily20240311-generic   

**Issue/Bug Description:**
breaks entire system, seems to spit information about looking for encrypted partitions, and doesnt boot, this system has no encryption enabled on it during the original install, system will not boot, had to revert to  linux-image-6.2.6-76060206-generic    and use apt to hold the version

**Steps to reproduce (if you know):**
im not sure,  maybe do not use encryption on the disk?  i  have no idea why its giving an error about encrypted devices not existing and failing to boot. i have no idea how to reproduce this on other hardware.

**Expected behavior:**
boot up normally

**Other Notes:**
hardware is a "MacBookAir6,1" default configuration nothing modified.

# lspci
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 09)
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
00:15.0 DMA controller: Intel Corporation 8 Series Low Power Sub-System DMA (rev 04)
00:15.4 Serial bus controller: Intel Corporation 8 Series SPI Controller #1 (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
00:1c.1 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 2 (rev e4)
00:1c.2 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 3 (rev e4)
00:1c.4 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 5 (rev e4)
00:1c.5 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 6 (rev e4)
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
02:00.0 Multimedia controller: Broadcom Inc. and subsidiaries 720p FaceTime HD Camera
03:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4360 802.11ac Wireless Network Adapter (rev 03)
04:00.0 SATA controller: Toshiba Corporation Device 010b (rev 14)
05:00.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
06:00.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
06:03.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
06:04.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
06:05.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
06:06.0 PCI bridge: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)
07:00.0 System peripheral: Intel Corporation DSL3510 Thunderbolt Controller [Cactus Ridge 4C 2012] (rev 03)

# lscpu
Arquitectura:                            x86_64
  modo(s) de operación de las CPUs:      32-bit, 64-bit
  Address sizes:                         39 bits physical, 48 bits virtual
  Orden de los bytes:                    Little Endian
CPU(s):                                  4
  Lista de la(s) CPU(s) en línea:        0-3
ID de fabricante:                        GenuineIntel
  Nombre del modelo:                     Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Familia de CPU:                      6
    Modelo:                              69
    Hilo(s) de procesamiento por núcleo: 2
    Núcleo(s) por «socket»:              2
    «Socket(s)»                          1
    Revisión:                            1
    CPU MHz máx.:                        2600.0000
    CPU MHz mín.:                        800.0000
    BogoMIPS:                            3799.65
    Indicadores:                         fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx f
                                         xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_
                                         good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est t
                                         m2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes
                                          xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_sha
                                         dow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsa
                                         veopt dtherm ida arat pln pts md_clear flush_l1d
Virtualization features:                 
  Virtualización:                        VT-x
Caches (sum of all):                     
  L1d:                                   64 KiB (2 instances)
  L1i:                                   64 KiB (2 instances)
  L2:                                    512 KiB (2 instances)
  L3:                                    3 MiB (1 instance)
NUMA:                                    
  Modo(s) NUMA:                          1
  CPU(s) del nodo NUMA 0:                0-3
Vulnerabilities:                         
  Itlb multihit:                         KVM: Mitigation: VMX disabled
  L1tf:                                  Mitigation; PTE Inversion; VMX vulnerable
  Mds:                                   Vulnerable; SMT vulnerable
  Meltdown:                              Vulnerable
  Mmio stale data:                       Unknown: No mitigations
  Retbleed:                              Not affected
  Spec store bypass:                     Vulnerable
  Spectre v1:                            Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
  Spectre v2:                            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
  Srbds:                                 Vulnerable
  Tsx async abort:                       Not affected

# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 05ac:0290 Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 001 Device 006: ID 05ac:828f Apple, Inc. Bluetooth USB Host Controller
Bus 001 Device 002: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Bus 001 Device 008: ID 18d1:4ee8 Google Inc. Nexus/Pixel Device (MIDI)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

# dmidecode
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 2.4 present.
43 structures occupying 2605 bytes.
Table at 0x8CD10000.

Wrong DMI structures length: 2605 bytes announced, only 2387 bytes available.
Handle 0x0000, DMI type 4, 35 bytes
Processor Information
	Socket Designation: U3E1
	Type: Central Processor
	Family: Core i5
	Manufacturer: Intel(R) Corporation
	ID: 51 06 04 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 69, Stepping 1
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
	Voltage: 0.9 V
	External Clock: 25 MHz
	Max Speed: 1300 MHz
	Current Speed: 1300 MHz
	Status: Populated, Enabled
	Upgrade: Socket BGA1168
	L1 Cache Handle: 0x0002
	L2 Cache Handle: 0x0003
	L3 Cache Handle: 0x0004
	Serial Number: To Be Filled By O.E.M.
	Asset Tag: To Be Filled By O.E.M.
	Part Number: Not Specified

Handle 0x0001, DMI type 7, 19 bytes
Cache Information
	Socket Designation: Not Specified
	Configuration: Enabled, Not Socketed, Level 1
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 64 kB
	Maximum Size: 64 kB
	Supported SRAM Types:
		Asynchronous
	Installed SRAM Type: Asynchronous
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Data
	Associativity: 8-way Set-associative

Handle 0x0002, DMI type 7, 19 bytes
Cache Information
	Socket Designation: Not Specified
	Configuration: Enabled, Not Socketed, Level 1
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 64 kB
	Maximum Size: 64 kB
	Supported SRAM Types:
		Asynchronous
	Installed SRAM Type: Asynchronous
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Instruction
	Associativity: 8-way Set-associative

Handle 0x0003, DMI type 7, 19 bytes
Cache Information
	Socket Designation: Not Specified
	Configuration: Enabled, Not Socketed, Level 2
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 512 kB
	Maximum Size: 512 kB
	Supported SRAM Types:
		Asynchronous
	Installed SRAM Type: Asynchronous
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 8-way Set-associative

Handle 0x0004, DMI type 7, 19 bytes
Cache Information
	Socket Designation: Not Specified
	Configuration: Enabled, Not Socketed, Level 3
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 3 MB
	Maximum Size: 3 MB
	Supported SRAM Types:
		Asynchronous
	Installed SRAM Type: Asynchronous
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 12-way Set-associative

Handle 0x0005, DMI type 16, 15 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: None
	Maximum Capacity: 8 GB
	Error Information Handle: Not Provided
	Number Of Devices: 2

Handle 0x0006, DMI type 130, 186 bytes
OEM-specific Type
	Header and Data:
		82 BA 06 00 07 00 00 00 B0 00 91 20 F1 03 04 11
		05 0B 03 11 01 08 0A 00 00 01 78 78 90 50 90 11
		50 E0 10 04 3C 3C 01 90 00 00 00 00 00 00 00 00
		00 A8 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80
		AD 01 00 00 00 00 00 00 58 5F 48 39 43 43 4E 4E
		4E 38 4A 54 4D 4C 41 52 2D 4E 54 4D 00 00 80 AD
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00

Handle 0x0007, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x0005
	Error Information Handle: No Error
	Total Width: Unknown
	Data Width: Unknown
	Size: 2 GB
	Form Factor: SODIMM
	Set: None
	Locator: DIMM0
	Bank Locator: BANK 0
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1600 MT/s
	Manufacturer: 0x80AD
	Serial Number: 0x00000000
	Asset Tag: Unknown
	Part Number: 0x483943434E4E4E384A544D4C41522D4E544D
	Rank: Unknown
	Configured Memory Speed: Unknown

Handle 0x0008, DMI type 130, 186 bytes
OEM-specific Type
	Header and Data:
		82 BA 08 00 09 00 00 00 B0 00 91 20 F1 03 04 11
		05 0B 03 11 01 08 0A 00 00 01 78 78 90 50 90 11
		50 E0 10 04 3C 3C 01 90 00 00 00 00 00 00 00 00
		00 A8 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80
		AD 01 00 00 00 00 00 00 58 5F 48 39 43 43 4E 4E
		4E 38 4A 54 4D 4C 41 52 2D 4E 54 4D 00 00 80 AD
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00

Handle 0x0009, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x0005
	Error Information Handle: No Error
	Total Width: Unknown
	Data Width: Unknown
	Size: 2 GB
	Form Factor: SODIMM
	Set: None
	Locator: DIMM0
	Bank Locator: BANK 1
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1600 MT/s
	Manufacturer: 0x80AD
	Serial Number: 0x00000000
	Asset Tag: Unknown
	Part Number: 0x483943434E4E4E384A544D4C41522D4E544D
	Rank: Unknown
	Configured Memory Speed: Unknown

Handle 0x000A, DMI type 19, 15 bytes
Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x000FFFFFFFF
	Range Size: 4 GB
	Physical Array Handle: 0x0005
	Partition Width: 0

Handle 0x000B, DMI type 0, 24 bytes
BIOS Information
	Vendor: Apple Inc.
	Version: 478.0.0.0.0
	Release Date: 01/13/2023
	ROM Size: 8 MB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		ACPI is supported
		IEEE 1394 boot is supported
		Smart battery is supported
		Function key-initiated network boot is supported
	BIOS Revision: 0.1

Handle 0x000C, DMI type 1, 27 bytes
System Information
	Manufacturer: Apple Inc.
	Product Name: MacBookAir6,1
	Version: 1.0
	Serial Number: C02L98GGF5N7
	UUID: f6136c4e-c46f-815e-9ebf-440e33c6cbb6
	Wake-up Type: Power Switch
	SKU Number: System SKU#
	Family: MacBook Air

Handle 0x000D, DMI type 2, 16 bytes
Base Board Information
	Manufacturer: Apple Inc.
	Product Name: Mac-35C1E88140C3E6CF
	Version: MacBookAir6,1
	Serial Number: C0233520540FD0CAA
	Asset Tag: Base Board Asset Tag#
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Part Component
	Chassis Handle: 0x000E
	Type: Motherboard
	Contained Object Handles: 0

Handle 0x000E, DMI type 3, 21 bytes
Chassis Information
	Manufacturer: Apple Inc.
	Type: Notebook
	Lock: Not Present
	Version: Mac-35C1E88140C3E6CF
	Serial Number: C02L98GGF5N7
	Asset Tag: Not Specified
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Other
	Security Status: Other
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: Unspecified
	Contained Elements: 0

Handle 0x000F, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: None
	External Reference Designator: USB0
	External Connector Type: Access Bus (USB)
	Port Type: USB

Handle 0x0010, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: None
	External Reference Designator: USB1
	External Connector Type: Access Bus (USB)
	Port Type: USB

Handle 0x0011, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: Other
	External Reference Designator: Mini DisplayPort
	External Connector Type: None
	Port Type: Other

Handle 0x0012, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: Other
	External Reference Designator: HDMI
	External Connector Type: None
	Port Type: Other

Handle 0x0013, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: Other
	External Reference Designator: Microphone
	External Connector Type: None
	Port Type: Other

Handle 0x0014, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: Other
	External Reference Designator: Speaker
	External Connector Type: None
	Port Type: Other

Handle 0x0015, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: None
	External Reference Designator: MagSafe DC Power
	External Connector Type: Other
	Port Type: Other

Handle 0x0016, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: None
	External Reference Designator: Audio Line Out
	External Connector Type: Mini Jack (headphones)
	Port Type: Audio Port

Handle 0x0017, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: None
	Internal Connector Type: None
	External Reference Designator: SD Card Reader
	External Connector Type: Access Bus (USB)
	Port Type: USB

Handle 0x0018, DMI type 9, 13 bytes
System Slot Information
	Designation: AirPort
	Type: x1 PCI Express
	Current Usage: Available
	Length: Short
	ID: 0
	Characteristics:
		3.3 V is provided
		Hot-plug devices are supported
		SMBus signal is supported

Handle 0x0019, DMI type 9, 13 bytes
System Slot Information
	Designation: Thunderbolt Slot 1
	Type: 32-bit PCI
	Current Usage: Available
	Length: Long
	ID: 2
	Characteristics:
		3.3 V is provided
		PME signal is supported
		Hot-plug devices are supported
		SMBus signal is supported

Handle 0x001A, DMI type 9, 13 bytes
System Slot Information
	Designation: Thunderbolt Slot 2
	Type: 32-bit PCI
	Current Usage: Available
	Length: Long
	ID: 3
	Characteristics:
		3.3 V is provided
		PME signal is supported
		Hot-plug devices are supported
		SMBus signal is supported

Handle 0x001B, DMI type 9, 13 bytes
System Slot Information
	Designation: Thunderbolt Slot 3
	Type: 32-bit PCI
	Current Usage: Available
	Length: Long
	ID: 4
	Characteristics:
		3.3 V is provided
		PME signal is supported
		Hot-plug devices are supported
		SMBus signal is supported

Handle 0x001C, DMI type 9, 13 bytes
System Slot Information
	Designation: Thunderbolt Slot 4
	Type: 32-bit PCI
	Current Usage: Available
	Length: Long
	ID: 5
	Characteristics:
		3.3 V is provided
		PME signal is supported
		Hot-plug devices are supported
		SMBus signal is supported

Handle 0x001D, DMI type 10, 6 bytes
On Board Device Information
	Type: Video
	Status: Enabled
	Description: Integrated Video Controller

Handle 0x001E, DMI type 10, 6 bytes
On Board Device Information
	Type: Sound
	Status: Enabled
	Description: Azalia Audio Codec

Handle 0x001F, DMI type 10, 6 bytes
On Board Device Information
	Type: Other
	Status: Enabled
	Description: SATA

Handle 0x0020, DMI type 11, 5 bytes
OEM Strings
	String 1: Apple ROM Version.  Model:        MBA61.  EFI Version:  478.0.0
	String 2: .0.0.  Built by:     root@wwl2t.  Date:         Fri Jan 13 17:4
	String 3: 7:58 PST 2023.  Revision:     478 (B&I).  ROM Version:  F000_B0
	String 4: 0.  Build Type:   Official Build, Release.  Compiler:     clang
	String 5: -1403.0.22.8.

Handle 0x0021, DMI type 12, 5 bytes
System Configuration Options

Handle 0x0022, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 1
		<BAD INDEX>
	Currently Installed Language: Not Specified

Handle 0x0023, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected

Handle 0x0024, DMI type 131, 6 bytes
OEM-specific Type
	Header and Data:
		83 06 24 00 05 06

Handle 0x0025, DMI type 128, 96 bytes
OEM-specific Type
	Header and Data:
		80 60 25 00 03 00 00 00 77 F5 0B FB FF FF FF FF
		02 00 03 00 00 00 00 00 00 00 99 FF FF FF B2 FF
		00 00 B3 FF FF FF DD FF 00 00 E1 FF FF FF E3 FF
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
		00 00 00 00 00 00 00 00 0D 00 00 00 FF FF FF FF

Handle 0x0026, DMI type 133, 12 bytes
OEM-specific Type
	Header and Data:
		85 0C 26 00 02 00 00 00 00 00 00 00

Handle 0x0027, DMI type 221, 26 bytes
OEM-specific Type
	Header and Data:
		DD 1A 27 00 03 01 00 01 08 00 00 00 02 00 00 00
		00 26 00 03 00 01 03 00 01 00
	Strings:
		Reference Code - CPU
		uCode Version
		TXT ACM version

Invalid entry length (0). DMI table is broken! Stop.

# lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0           7:0    0     4K  1 loop  /snap/bare/5
loop1           7:1    0  63.9M  1 loop  /snap/core20/2264
loop2           7:2    0 349.7M  1 loop  /snap/gnome-3-38-2004/143
loop3           7:3    0  91.7M  1 loop  /snap/gtk-common-themes/1535
loop4           7:4    0  78.4M  1 loop  /snap/icloud-for-linux/240
loop5           7:5    0  38.7M  1 loop  /snap/snapd/21465
sda             8:0    0   113G  0 disk  
├─sda1          8:1    0  1022M  0 part  /boot/efi
├─sda2          8:2    0     4G  0 part  /recovery
├─sda3          8:3    0   104G  0 part  /
└─sda4          8:4    0     4G  0 part  
  └─cryptswap 253:0    0     4G  0 crypt [SWAP]
zram0         252:0    0   3.8G  0 disk  [SWAP]

**Comment by MarcSeebold** [comment]
Same here. This broke my ethernet driver:
```
ERROR (dkms apport): kernel package linux-headers-6.8.0-76060800daily20240311-generic is not supported
Error! Bad return status for module build on kernel: 6.8.0-76060800daily20240311-generic (x86_64)
Consult /var/lib/dkms/r8168/8.049.02/build/make.log for more information.
dpkg: error processing package r8168-dkms (--configure):
 installed r8168-dkms package post-installation script subprocess returned error exit status 10
```

excerpt from make.log:
```
/var/lib/dkms/r8168/8.049.02/build/r8168_n.c: In function ‘rtl8168_get_drvinfo’:
/var/lib/dkms/r8168/8.049.02/build/r8168_n.c:5124:17: error: implicit declaration of function ‘strlcpy’;
 did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
 5124 |                 strlcpy(info->fw_version, rtl_fw->version,
      |                 ^~~~~~~
      |                 strscpy
```
