### ISSUE TITLE
ZeroMQ stops compiling on 20.10

### ISSUE THREAD

**Issue by adrianRodriguez123** [pop-os/pop#1419]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
ZeroMQ. NodeJS 15.2.1. NPM 7.0.8

**Issue/Bug Description:**
Before updating, ZeroMQ compiles perfectly. After updating to 20.10, ZeroMQ  doesn't compile anymore. When I run a simple js file with only   ```const zmq = require('zeromq')```  it gives me this error:
```
node:internal/modules/cjs/loader:922
  throw err;
  ^

Error: Cannot find module '../build/Release/zmq.node'
Require stack:
- /home/myuser/node_modules/zeromq/lib/index.js
- /home/myuser/node_modules/zeromq/index.js
- /home/myuser/Documents/Lab/fuentes/publicadorServer.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/myuser/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/myuser/node_modules/zeromq/lib/index.js',
    '/home/myuser/node_modules/zeromq/index.js',
    '/home/myuser/Documents/Lab/fuentes/publicadorServer.js'
  ]
}
```

**Expected behavior:**
zeromq should compile perfectly.

**Other Notes:**

Please, it is really urgent.
It's my first time posting an issue sorry if I am making any mistake

**Comment by adrianRodriguez123** [comment]
I could fixed it with the command ```npm rebuild``` .  I guess, installing a new version of node and the new operating system version make necessary to rebuild it, but I still don't understand that, if i uninstall nodejs and npm, why it was not working. Fortunately, it's all fixed.
