### ISSUE TITLE
Kernel was updated but the package for the rtl8821ce wifi chipset was not.

### ISSUE THREAD

**Issue by ZIGAG4899** [pop-os/pop#1956]
So i picked up pop os yesterday and my wifi was slow and i found out my chipset was rtl8821ce so i tried to install the package for it to speed up my wifi, but i was getting errors and it wouldn't install the package, so to figure out the issue i went to ubuntu and installed the package there. the package installed just fine.

**Comment by ZIGAG4899** [comment]
these were the errors. also sorry for replying late.

ERROR (dkms apport): kernel package linux-headers-5.13.0-7614-generic is
not supportedError! Bad return status for module build on kernel:
5.13.0-7614-generic (x86_64)Consult /var/lib/dkms/rtl8821ce/
5.5.2.1/build/make.log for more information.dpkg: error processing package
rtl8821ce-dkms (--configure): installed rtl8821ce-dkms package
post-installation script subprocess returned error exit status 10Errors
were encountered while processing: rtl8821ce-dkmsE: Sub-process
/usr/bin/dpkg returned an error code (1)

**Comment by imakiro** [comment]
Issue is still present 
```
Loading new rtl8821ce-5.5.2.1 DKMS files...
Building for 5.15.11-76051511-generic
Building initial module for 5.15.11-76051511-generic
ERROR (dkms apport): kernel package linux-headers-5.15.11-76051511-generic is no
t supported
Error! Bad return status for module build on kernel: 5.15.11-76051511-generic (x
86_64)
Consult /var/lib/dkms/rtl8821ce/5.5.2.1/build/make.log for more information.
```

**Comment by crazyaccess** [comment]
And if you use the [tomaspinho's rtl8821ce driver](https://github.com/tomaspinho/rtl8821ce) and install it manually, it still will crash the kernel.

**Comment by Nan123721** [comment]
This driver appears to not being needed since there is one in the kernel. A friend had Pop prompt that driver for install, even though it is not needed, I may open an issue about it.

**Comment by poolborges** [comment]
### Machine

PC
* Dell Inc. Vostro 3420
* Mem: 16.0 GiB
* CPU: 12th Gen Intel® Core™ i7-1255U × 12 

SO
* Pop!_OS 22.04 LTS
`Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1713206908~22.04~3a62479 SMP PREEMPT_DYNAMIC Mon A x86_64 x86_64 x86_64 GNU/Linux`

### Why (Fail to build)

rtl8821ce-dkms (rtl8821ce-5.5.2.1) fail to build with new kernel 

Found 12 "error:’" in make.log (see reference  for more info)
 
* error: too many arguments to function ‘netif_napi_add’
** kernel 6.1 API change


### Remediation

Remove the 
`sudo apt remove rtl8821ce-dkms` 

Package manger - Hold (To not be installed or updated)
`sudo apt-mark hold rtl8821ce-dkms`

### References

* [rtl8821ce-dkms make.log](https://github.com/pop-os/pop/files/15021410/make.log)
* https://launchpad.net/ubuntu/+source/rtl8821ce/+bugs
