### ISSUE TITLE
Newest bcmwl drivers not working with BCM4352

### ISSUE THREAD

**Issue by Elektrobomb** [pop-os/pop#3474]
I just updated my bcmwl drivers from pop shop and now my WiFi adapter isn't showing up in the usual places.  

I found [this Reddit post](https://www.reddit.com/r/pop_os/s/a7gC3tzjsV) with a couple of other people reporting similar issues a few hours ago so I don't think I'm alone.  

Context / stuff I have tried so far:
lspci shows the wifi adapter is still connected:
```
    08:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4352 802.11ac Wireless Network Adapter (rev 03)
```

dkms status gives:
```
    $ dkms status
    nvidia/565.77, 6.9.3-76060903-generic, x86_64: installed
    system76/1.0.17~1735251933~22.04~f01bffd, 6.9.3-76060903-generic, x86_64: installed
    system76_acpi/1.0.2~1719257749~22.04~7bae1af, 6.9.3-76060903-generic, x86_64: installed (original_module exists)
    system76-io/1.0.4~1732138800~22.04~fc71f15, 6.9.3-76060903-generic, x86_64: installed
    xone/v0.3-57-g29ec357, 6.9.3-76060903-generic, x86_64: installed
```

Reinstalling bcmwl-kernel-source gives:
```
    $ sudo apt-get reinstall bcmwl-kernel-source
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
    Need to get 0 B/13.4 kB of archives.
    After this operation, 0 B of additional disk space will be used.
    (Reading database ... 212952 files and directories currently installed.)
    Preparing to unpack .../bcmwl-kernel-source_6.30.223.271+bdcom-0ubuntu10pop2~1741059100~22.04~a8dfbbc_amd64.deb ...
    Unpacking bcmwl-kernel-source (6.30.223.271+bdcom-0ubuntu10pop2~1741059100~22.04~a8dfbbc) over (6.30.223.271+bdcom-0ubuntu10pop2~1741059100~22.04~a8dfbbc) ...
    Setting up bcmwl-kernel-source (6.30.223.271+bdcom-0ubuntu10pop2~1741059100~22.04~a8dfbbc) ...
```
I have tried purging and reinstalling the driver but no dice so far :/

**Comment by fovecsernyes** [comment]
Same here, mine is broken for 2 days.

**Comment by Elektrobomb** [comment]
@fovecsernyes 

I have found a workaround!

run the following:

`sudo apt remove bcmwl-kernel-source`
`sudo apt install bcmwl-kernel-source="6.30.223.271+bdcom-0ubuntu10~22.04.1"`

This should install a version of the driver which is working (at least for my PC)

**Comment by fovecsernyes** [comment]
Thanks, it resolves the issue. Do not forget to run

`apt-mark hold bcmwl-kernel-source` to prevent updating until it gets resolved.

**Comment by ashleytowner** [comment]
I'm also having this same issue; The solution of the following:

```
sudo apt remove bcmwl-kernel-source
sudo apt install bcmwl-kernel-source="6.30.223.271+bdcom-0ubuntu10~22.04.1"
```

worked when I was on kernel version `6.9.3-76060903-generic` but now I've updated (again via pop-shop,to `6.12.10-76061203-generic`) it seems to have all broken again, and installing that specific version doesn't work.

**Comment by mmstick** [comment]
The latest version of broadcom-sta-dkms is required for Linux 6.12

**Comment by infinitewarp** [comment]
I was just hit by this in the latest update too. My wireless card info in case it helps anyone else find this:

```
$ lspci -nn -d 14e4:
04:00.0 Network controller [0280]: Broadcom Inc. and subsidiaries BCM4360 802.11ac Dual Band Wireless Network Adapter [14e4:43a0] (rev 03)
```

I am also only able to get this specific version of `bcmwl-kernel-source` to succeed on kernels _older_ than 6.12:

```sh
sudo apt remove bcmwl-kernel-source
sudo apt install bcmwl-kernel-source="6.30.223.271+bdcom-0ubuntu10~22.04.1"
```

I had the same experience as @amadeuspzs. The install command fails on the current/latest `6.12.10` but seems to succeed (despite exiting with an error at the end) for older kernels. When it tries to build for 6.12, it displays this error message and exits with return code `100`:

```
Building initial module for 6.12.10-76061203-generic
ERROR (dkms apport): kernel package linux-headers-6.12.10-76061203-generic is not supported
Error! Bad return status for module build on kernel: 6.12.10-76061203-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log for more information.
dpkg: error processing package bcmwl-kernel-source (--configure):
 installed bcmwl-kernel-source package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 bcmwl-kernel-source
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

For reference, that `/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log` contains the following:

```
DKMS make.log for bcmwl-6.30.223.271+bdcom for kernel 6.12.10-76061203-generic (x86_64)
Wed Mar 12 10:17:51 PM EDT 2025
make: Entering directory '/usr/src/linux-headers-6.12.10-76061203-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:59:10: fatal error: asm/unaligned.h: No such file or directory
   59 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:40:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c: In function ‘wl_set_auth_type’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.h:52:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
   52 |         if (wl_dbg_level & WL_DBG_DBG) {                        \
      |            ^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:805:17: note: in expansion of macro ‘WL_DBG’
  805 |                 WL_DBG(("network eap\n"));
      |                 ^~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:806:9: note: here
  806 |         default:
      |         ^~~~~~~
make[1]: *** [/usr/src/linux-headers-6.12.10-76061203-generic/Makefile:1943: /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.10-76061203-generic'
```

Fortunately in my case, `6.9.3` was the most recent _older_ kernel I still had installed, and it succeeded _before_ this failure occurred for 6.12. So, I also used `kernelstub` to switch to `6.9.3`, and after reboot, my wifi is working again.

> The latest version of broadcom-sta-dkms is required for Linux 6.12. Older broadcom drivers aren't compatible.

@mmstick I am not familiar with the development history of `broadcom-sta-dkms` and `bcmwl-kernel-source`. Do you know if they are actively maintained and might get updated to build correctly on 6.12? Or do you suspect our cards are basically EOL and we need to start finding replacements if we want to use modern kernels?

**Comment by infinitewarp** [comment]
I don't follow Debian development, but just searching around I landed on this bug report from a couple months ago that suggests it may be fixed somewhere upstream. Maybe there is hope?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1088844

>  broadcom-sta-dkms 6.30.223.271-24 fails to compile with kernel 6.12.1

Possible patch solution in this gist: https://gist.github.com/vejeta/a44e792f37811f7f6e47445b03760d87

And maybe the fix is already available in Debian unstable:

> We believe that the bug you reported is fixed in the latest version of
> broadcom-sta, which is due to be installed in the Debian FTP archive.
> ...
> Description:
> broadcom-sta-common - Common files for the Broadcom STA Wireless driver
> broadcom-sta-dkms - dkms source for the Broadcom STA Wireless driver
> broadcom-sta-source - Source for the Broadcom STA Wireless driver
>Closes: [838735](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838735) [1016882](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016882) [1088844](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1088844) [1090964](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1090964)

**Comment by mmstick** [comment]
@infinitewarp You must use the broadcom package we released recently with 6.12. The older broadcom package is not compatible with 6.12.

**Comment by ashleytowner** [comment]
> The latest version of broadcom-sta-dkms is required for Linux 6.12. Older broadcom drivers aren't compatible.

@mmstick I believe I _do_ have the latest version of `broadcom-sta-dkms` installed (`6.30.223.271+bdcom-0ubuntu10pop2~1741059100~22.04~a8dfbbc`) but wifi still isn't working.

**Comment by infinitewarp** [comment]
As far as I can tell, `broadcom-sta-dkms` simply isn't working for reasons I cannot fathom. 😕 When I look at the package description for `broadcom-sta-dkms`, it says: 

```
Broadcom STA is a binary-only device driver to support the following IEEE
802.11a/b/g/n wireless network cards: BCM4311-, BCM4312-, BCM4313-,
BCM4321-, BCM4322-, BCM43142-, BCM43224-, BCM43225-, BCM43227-, BCM43228-,
BCM4331-, BCM4360-, and BCM4352-based hardware.
```

And my model _is_ listed there which I assume means it should just work. I have BCM4360 (`[14e4:43a0] (rev 03)` per my earlier comment). I'm pretty sure I tried broadcom-sta or some other drivers long ago, and only `bcmwl-kernel-source` ever worked for my hardware. For context, there is an _ancient_ (originally posted 2011 but last updated in 2024) AskUbunutu answer [here](https://askubuntu.com/a/60395/1508356) that I know I followed several times over the years whenever PopOS updates broke my wireless adapter, and I'm 100% sure that's how I originally ended up with `bcmwl-kernel-source`. My first instinct this week was to go check that answer for any new advice, but if what I read in this thread is correct, that answer's information may no longer apply with 6.12.

Regardless, my latest attempt to get things working:
* I ran `kernelstub` to switch back to the latest kernel 6.12.10, rebooted, and confirmed with `uname -a` that I was indeed back to 6.12.10.
* I ran `apt update`, `apt purge bcmwl-kernel-source broadcom-sta-dkms broadcom-sta-source`, `apt autoclean`, `apt autoremove`, and restarted so that all traces of any previous drivers were gone.
* I ran `apt install broadcom-sta-dkms` and watched it claim to update the kernel successfully.
* I restarted, and yet still my wifi card doesn't work. `lspci` shows the device is connected, but `dkms status` does not show the device, and `modprobe wl` fails (`FATAL: Module wl not found`). On the older kernel using `bcmwl-kernel-source`, `modprobe wl` succeeded and the device was listed under `dkms status`.

For now, I have returned to kernel 6.9, reinstalled `bcmwl-kernel-source` (pinned to the older version mentioned above), and found my wifi adapter immediately working perfectly again. 🤷  I can't keep this system tethered to another device over ethernet, but I can give troubleshooting 6.12 another try over the weekend if anyone has more ideas.

@mmstick Can you suggest anything else to try or look for when I switch back to 6.12? Are there any logs I can dig through for more information? I feel like I must be overlooking something obvious, but I can't see what it could be. I can dump any command outputs or share any logs if you can think of some that might be useful.

**Comment by fovecsernyes** [comment]
Hi, this still seems like an issue.

**Comment by ashleytowner** [comment]
@wins-m are you saying you're experiencing the same issue with the new card as well?

**Comment by Nathambetant** [comment]
Same issue here. Reverting back to previous version of Pop Os.

**Comment by infinitewarp** [comment]
> Fresh install of Pop!_OS here - experiencing this, also. Does not get fixed when I kernelstub an older init/kernel & use the backlevel workaround. This used to work for me. Im a returning user to Pop!_OS, but now Im just considering going plain Ubuntu since this is completely broken here.

I have one other suggestion if you haven't already reinstalled another distro, @aaaaaaaalex. At one point in my journey, I got back to the old kernel and installed the old driver, and `wl` _seemed_ to be available, but actual wifi _still_ wasn't showing up correctly. A search through my boot log with `journalctl -b 0` revealed this suspicious error:

```
b43-phy0: Broadcom 4360 WLAN found (core revision 42)
b43-phy0 ERROR: FOUND UNSUPPORTED PHY (Analog 12, Type 11 (AC), Revision 1)
b43 bcma0:1: probe with driver b43 failed with error -95
Broadcom 43xx driver loaded [ Features: PNL ]
```

I was able to, at least for that session, unload all related Broadcom modules and reload the correct module using the following commands:

```sh
sudo modprobe -r b43
sudo modprobe -r bcma
sudo modprobe -r wl
sudo modprobe wl
```

The wifi symbol immediately appeared in my top bar as soon as the last command executed. Not sure if this is the case for anyone else, but hopefully it's another clue to help you out.

**Comment by mmstick** [comment]
I think all you need is to set `blacklist bcma` in a modprobe conf.

**Comment by mmstick** [comment]
Seems the broadcom package should already be blacklisted in `/etc/modprobe.d/broadcom-sta-dkms.conf`

**Comment by infinitewarp** [comment]
> Seems the conflicting broadcom modules should already be blacklisted in `/etc/modprobe.d/broadcom-sta-dkms.conf`

…but that config file appears to be provided by `broadcom-sta-dkms` which, as noted above, many of us have manually uninstalled because it doesn't seem to work for us.

But thank you for this reminder about the modprobe blacklist command. 🙂 I have manually written the same lines into a custom `/etc/modprobe.d/` file for now.

That being said, @mmstick do you have any other suggestions of things to look for or try for those of us whose "supported" Broadcom cards don't seem to work with 6.12 + `broadcom-sta-dkms`?

**Comment by mmstick** [comment]
I would not manually remove it since it is required by the proprietary driver. The open source drivers in the blacklist conflict with the wl module .

**Comment by Iminy99** [comment]
How can do to fix this issue on kernel 6.12 with my Broadcom BCM94360CD, i wait an update or i do to operate manually?

**Comment by fovecsernyes** [comment]
Is there a plan to fix this?

**Comment by zaigham** [comment]
I have manually installed this package to get the WiFi working again.

https://packages.debian.org/unstable/broadcom-sta-dkms

Basically, I download the newest package which is now fixed from Debian upstream manually. Installed it for 6.12 kernel by using :

`apt install ./broadcom-sta-dkms_6.30.223.271-26_amd64.deb`

**Comment by TimmermanV** [comment]
How long could it take for this fix to find its way to PopOS as a regular update?

**Comment by mmstick** [comment]
Probably fixed by https://github.com/pop-os/bcmwl/pull/9

**Comment by Iminy99** [comment]
when will the same update that was released on debian be released on pop os? because the update deb file works great but then during the updates it overwrites it

**Comment by TimmermanV** [comment]
I haven't tried that package yet, but I think you could use `apt-mark hold broadcom-sta-dkms` to keep that package version and prevent automatic updates.

**Comment by mmstick** [comment]
You can install the update early by adding the pre-release master staging repository with apt-manage

```
sudo apt-manage add popdev:master
sudo apt update 
sudo apt full-upgrade
```

**Comment by Iminy99** [comment]
but the official fix update, will it be released soon?

**Comment by leviport** [comment]
Yes

**Comment by nilesjohnson** [comment]
> You can install the update early by ...

I just tried this and it worked perfectly.  Thanks everyone for helping me get this resolved so quickly.  Having struggled with the wifi on this 10yo laptop too many times over the years, I'm astounded at how well this went!! I'm once again impressed with the S76 + pop support.

**Comment by gmoraitis** [comment]
Hi , any news about the official update? I switched to Ubuntu 24 lts for a while until the fix, and i don't have a machine to test if the wifi is working.. If you have time, can you please post a message here when it's done? Thank you very much for your time and effort.

**Comment by Terneptha** [comment]
> You can install the update early by adding the pre-release master staging repository with apt-manage
> 
> ```
> sudo apt-manage add popdev:master
> sudo apt update 
> sudo apt full-upgrade
> ```

This worked for me (Wifi adapter not found after kernel upgrade to 6.12...) Thanks!

**Comment by amadeuspzs** [comment]
> > You can install the update early by adding the pre-release master staging repository with apt-manage
> > ```
> > sudo apt-manage add popdev:master
> > sudo apt update 
> > sudo apt full-upgrade
> > ```
> 
> This worked for me (Wifi adapter not found after kernel upgrade to 6.12...) Thanks!

Can also confirm this fix worked - thank you!

**Comment by Iminy99** [comment]
nothing official yet, when will it be released? I don't feel like adding unstable updates to have it

**Comment by leviport** [comment]
The fix should be released now. Sorry for the delay. The CI system put up a fight.

**Comment by aaaaaaaalex** [comment]
@infinitewarp big respect for being able to get that far!
Sadly for me I went and installed Arch a few days after my last comment 😂

**Comment by Iminy99** [comment]
How to remove the staging repository? Because not fix my problem, thx

**Comment by flowaves** [comment]
Thank you sincerely for your time !

> Hi,
> After experiencing the same problem and making several attempts, I finally **reinstalled Pop!_OS** then **blocked kernel updates** like this :
> `sudo apt-mark hold linux-image-generic`
> `sudo apt-mark hold linux-headers-generic`
> `sudo apt-mark hold linux-system76`
> `sudo apt-mark hold linux-base`
> `sudo apt-mark hold linux-image-6. 9.3-76060903-generic`
> `sudo apt-mark hold linux-headers-6.9.3-76060903-generic`
> That worked for me, I'll unblock that when there's a fix.

After unblocking all this, and doing the update, the problem reappears 🤔
Did it work for the others ?

**Comment by TimmermanV** [comment]
That's a yes for me. :-)
A few days ago I installed all updates after confirming it was no longer listing the broadcom update ending in a8dfbbc, but a different one. I updated the kernel and the broadcom driver packages. Everything appears to be working correctly. `uname -r` shows `6.12.10-76061203-generic` and my wifi is working and stable.
This is on a 2012 MacBook Pro, Network controller: Broadcom Inc. and subsidiaries BCM4331 802.11a/b/g/n (rev 02)

**Comment by ashleytowner** [comment]
Can also confirm that for me, after updating everything, I can get wifi on kernel version `6.12.10-76061203-generic`

**Comment by infinitewarp** [comment]
Latest updates fixed wifi for my BCM4360 too. 🎉 

My upgrade process, since I manually rolled back the kernel as described in my earlier comments, included:

* `sudo kernelstub -v -k ...` to switch back to the latest `6.12.10-76061203-generic` kernel.
* reboot
* observe broken wifi, and tether to another system over ethernet
* apply _all_ available package updates
* reboot
* disconnect ethernet

…and wifi successfully reconnected! Thank you very much to everyone who was involved in getting this fix published. ❤

**Comment by gmoraitis** [comment]
Worked for me also on Macbook pro 2012 non retina.
